compressionLevel: mixed

enableGlobalCache: true

packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"

plugins:
  - path: ./packages/yarn-plugin-scripts-cache/bundles/@yarnpkg/plugin-scripts-cache.js
    spec: "@yarnpkg/plugin-scripts-cache"
  - path: ./packages/yarn-plugin-scripts-cache-file/bundles/@yarnpkg/plugin-scripts-cache-file.js
    spec: "@yarnpkg/plugin-scripts-cache-file"
  - path: ./packages/yarn-plugin-scripts-cache-nexus/bundles/@yarnpkg/plugin-scripts-cache-nexus.js
    spec: "@yarnpkg/plugin-scripts-cache-nexus"
  - path: ./packages/yarn-plugin-scripts-cache-remote-statistics-client/bundles/@yarnpkg/plugin-scripts-cache-remote-statistics-client.js
    spec: "@yarnpkg/plugin-scripts-cache-remote-statistics-client"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
