packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: ./packages/yarn-plugin-scripts-cache/bundles/@yarnpkg/plugin-scripts-cache.js
    spec: "@yarnpkg/plugin-scripts-cache"
  - path: ./packages/yarn-plugin-scripts-cache-file/bundles/@yarnpkg/plugin-scripts-cache-file.js
    spec: "@yarnpkg/plugin-scripts-cache-file"
  - path: ./packages/yarn-plugin-scripts-cache-nexus/bundles/@yarnpkg/plugin-scripts-cache-nexus.js
    spec: "@yarnpkg/plugin-scripts-cache-nexus"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
