yarnPath: .yarn/releases/yarn-3.2.3.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: ./yarn-plugin-build-result-cache/bundles/@yarnpkg/plugin-build-result-cache.js
    spec: "@yarnpkg/plugin-build-result-cache"
