compressionLevel: mixed

enableGlobalCache: true

packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  eslint-config-react-app@7.0.1:
    dependencies:
      "@babel/plugin-syntax-flow": "npm:@babel/plugin-syntax-flow@^7.14.5"
      "@babel/plugin-transform-react-jsx": "npm:@babel/plugin-transform-react-jsx@^7.14.9"

plugins:
  - path: ./packages/yarn-plugin-scripts-cache/bundles/@yarnpkg/plugin-scripts-cache.js
    spec: "@yarnpkg/plugin-scripts-cache"
  - path: ./packages/yarn-plugin-scripts-cache-file/bundles/@yarnpkg/plugin-scripts-cache-file.js
    spec: "@yarnpkg/plugin-scripts-cache-file"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
